#Languages available: PT_BR(Portuguese), ES_ES(Spanish), EN_US(English), KO_KR(Korean), ZH_CH(Chinese), JA_JP (Japanese)
defaultLanguage: 'EN_US'
leaderboard:
 show-role: true

database:
 # Currently available database types: MongoDB, MySQL
 type: 'MySQL'
 mysql:
  # Use Hikari
  hikari: false
  # Use MariaDB driver
  mariadb: false
  # Host to access MySQL
  host: 'localhost'
  # Port to access MySQL
  port: '3306'
  # Database name in MySQL
  name: 'server'
  # MySQL access user
  user: 'root'
  # MySQL access password
  pass: ''
 mongodb:
   # MongoDB access URL
   # https://docs.mongodb.com/manual/reference/connection-string/
   url: ''

stats-skywars: true
stats-bedwars: true
stats-thebridge: true
stats-thepit: true
stats-duels: true

#If true, a hotbar will only work in the lobby world
interact-hotbar-world: true
#If you want click in other player and open menu statistics turn to true
click-player-menu: false
